name: Ubuntu-unittests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
      - name: Run verification tests against git
        run: |
          cd test
          bats -t .
      - name: Run unittests
        run: |
          cd test
          PYTHONPATH="../" python3 -m unittest
