name: unittests

on: [push]

jobs:
  Tests:
    strategy:
      matrix:
        platform: [macOS-latest, ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: Clone bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
      - name: Install bats - Windows
        if: matrix.platform == 'windows-latest'
        run: |
          cd bats-core
          ./install.sh $HOME
      - name: Install bats - Unix
        if: matrix.platform != 'windows-latest'
        run: |
          cd bats-core
          sudo ./install.sh /usr/local
      - name: Run unittests
        run: |
          cd test
          PYTHONPATH="../" python3 -m unittest test_index.py
      - name: Run Git conformance tests
        run: |
          cd test
          bats -t .
